### ISSUE TITLE
Aktualizacja Planety via GitHub Actions + cron

### ISSUE THREAD

**Issue by macbre** [macbre/nordic-feed#4]
https://lannonbr.com/blog/2019-12-09-git-commit-in-actions

```
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/15 * * * *'
```
